<?php

return [
    "header" => "Outsource Real Person",
    "info" => "If you want to outsource an eLearning designer, an educative video animator, or front-end or back-end developers, you are in the right place.",
    "people" => "Available People",
    "hire" => "Hire me",
    // za svakoga pojedinačno

    "irfank-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "irfank-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "irfank-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat...",

    "ibrahimz-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "ibrahimz-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "ibrahimz-about-short" => "Hi! I am Ibrahim Zubača, a wordpress developer focused on crafting great web experiences. Beside being a web developer, I am a photography hobbyist and travel/adventure lover.",

    "harism-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "harism-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "harism-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat.",

    "amerm-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "amerm-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "amerm-about-short" => "Hello! I'm Amer Masleša, a designer and animator focused on eLearning and multimedia design. I strive to create simple, original, and impactful user experiences. I can deliver the most modern and effective solutions. I'm always looking for new and exciting opportunities, so don't hesitate to get in touch.",

    "irfans-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "irfans-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "irfans-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat.",

    "aidar-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "aidar-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "aidar-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat.",

    "emirm-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "emirm-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "emirm-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat.",

    "florinb-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "florinb-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "florinb-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat.",

    "mirzao-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "mirzao-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "mirzao-about-short" => "Praesent posuere posuere tortor, id ultricies nisl ornare eu. Curabitur viverra risus quis dolor egestas suscipit. Sed posuere dolor non interdum congue. Nulla suscipit dignissim leo. Donec porttitor venenatis nunc nec dictum. Praesent volutpat purus vel tellus laoreet gravida. Donec eget aliquam neque, id consequat erat."
];
