<?php

return [
    "header" => "Outsource Real Person",
    "info" => "If you want to outsource an eLearning designer, an educative video animator, or front-end or back-end developers, you are in the right place.",
    "people" => "Available People",
    "hire" => "Hire me",
    // za svakoga pojedinačno

    "irfank-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "irfank-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "irfank-about-short" => "Experienced Learning Designer with a demonstrated history of working in the e-learning industry. Skilled in Articulate Storyline, Moodle and E-learning Implementation. Familiar with Adobe Photoshop, Adobe Captivate and Adobe Animate. Strong education professional graduated from School of Economics and Business Sarajevo.
    Additional is interested in Marketing, with a focus on Social Media Marketing, E-mail Marketing and Google Ads.",

    "ibrahimz-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "ibrahimz-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "ibrahimz-about-short" => "Hi! I am Ibrahim Zubača, a wordpress developer focused on crafting great web experiences. Beside being a web developer, I am a photography hobbyist and travel/adventure lover.",

    "harism-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "harism-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "harism-about-short" => "Hi, my name is Haris and I like writing code in multiple programming languages as well as working on interesting and new projects. I always look to learn new things in IT world, and currently I spend most of my time learning and mastering Machine Learning.
    ",

    "zulfom-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "zulfom-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "zulfom-about-short" => "Hi! I’m Zulfo, Full Stack Developer with 2 years of experience. I’m experienced with: PHP, Javascript, SQL, JSON, and also with HTML and CSS. I’m familiar with php frameworks - Symfony, Laravel, javascript frameworks - EmberJS, Polymer, and technologies like Git, Elasticsearch. I like complicated stuff :) , and I tend to grow my experience and knowledge. Check some of my work on my github page.",

    "irfans-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "irfans-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "irfans-about-short" => "The eLearning industry, as well as the production of courses in Articulate Storyline, represents a very effective and efficient way of transmitting information in the digital world. My workflow consists of creating visual layouts in Adobe Photoshop and Adobe Illustrator, as well as creating functional and complex interactions, as well as content gamification in Articulate Storyline, and also creating complex animations within Adobe Animate.",

    "aidar-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "aidar-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "aidar-about-short" => "Hi :) My name is Aida and I'm an e-learning designer. I have 11 years of experience in design and a desire to constantly learn new things. In my spare time I like to paint and to walk in the nature. My great love are my husband and my pets :)",

    "emirm-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "emirm-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "emirm-about-short" => "Hello, my name is Emir Mekić, I'm front-end and moodle developer who loves birds, nature and enjoys being outdoors. I don’t like to define myself by the work I’ve done. I define myself by the work I want to do. Skills can be taught, personality is inherent. I prefer to keep learning, continue challenging myself, and do interesting things that matter.",

    "florinb-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "florinb-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "florinb-about-short" => "On last several months, I made a big step forward in Web development experience. I worked on web based learning projects converting from all flash fromats to html5. If you are looking for a developer who can be very dedicated to your project, I am willing to take part :)",

    "mirzao-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "mirzao-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "mirzao-about-short" => "I have 3 years of experience in web and mobile applications design with different forms of back-end architecture (monolithic and microcontroller). I am primarily interested in back-end web and mobile applications design and support tools and technologies. The basic programming language that I use for designing  is PHP (Symfony and Laravel framework), while using DBMS as MySQL and SQL Server. As for the front-end of making web applications, I prefer using basic JavaScript to comply with the latest ECMA standards, but I also have experience in using its frameworks such as jQuery, Ember and Polymer.
    Also, I have a great interest in Cloud Technology such as Google Cloud Platform and technologies for application management on the server such as Docker and Kubernetes. More about my projects and my code you can see on my GitHub public repositories."
];
