<?php

return [
    "header" => "Unajmite pravu osobu",
    "info" => "Ako želite unajmiti eLearning dizajnera, edukacijskog video animatora, ili front-end ili back-end programera, na pravom ste mjestu.",
    "people" => "Dostupni ljudi",
    "hire" => "Unajmi me",
    // za svakoga pojedinačno

    "irfank-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "irfank-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "irfank-about-short" => "E-learning dizajner sa velikim radnim iskustvom u e-learning industriji.  Poznajem rad i aktivno koristim  Articulate Storyline, Moodle, E-learning Implementation, Adobe Photoshop, Adobe Captivate, and Adobe Animate. U pogledu formalnog obrazovanja, diplomirao sam na smjeru Razvoj poslovnih informacionih sistema na Ekonomskom fakultetu u Sarajevu.
    Pored navedenog sam zainteresiran za marketing, s fokusom na Social Media Marketing Social Media Marketing, e-mail marketing i Google oglase.",

    "ibrahimz-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "ibrahimz-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "ibrahimz-about-short" => "Ćao! Ja sam Ibrahim Zubača, WordPress developer fokusiran na stvaranje sjajnih web iskustava. Pored toga što sam web developer, ljubitelj sam fotogravije, putovanja i avanture.",

    "harism-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "harism-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "harism-about-short" => "Ja sam Haris i volim pisati kod u raznim programskim jezicima, i raditi na interesantnim i novim projektima. Uvijek gledam da naučim nove stvari u IT svijetu, a trenutno najviše vremena provodim na učenju i usavršavanju Machine Learning-a.",

    "zulfom-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "zulfom-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "zulfom-about-short" => "Ćao! Ja sam Zulfo, Full Stack Developer sa 2 godine iskustva. Imam iskustva sa: PHP, Javascript, SQL, JSON, kao i sa HTML-om i CSS-om. Imam iskustva sa php frameworks (Symfony, Laravel), javascript frameworks ( EmberJS, Polymer ) i tehnologije poput Git-a, Elasticsearch-a. Volim komplicirane stvari :), i tezim ka tome da prosirim svoje iskustvo i znanje. Pogledajte neke od mojih radova na mojoj github stranici.",

    "irfans-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "irfans-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "irfans-about-short" => "eLearning industrija, kao i sama produkcija kurseva u Articulate Storyline, za mene predstavlja veoma efikasan i vrlo učinkovit način prenošenja informacija u digitalnom svijetu. Moj workflow se sastoji u izradi vizualnih layouta u Adobe Photoshopu i Adobe Illustratoru, kao i kreiranje funkcionalnih i kompleksnih interakcija, kao i sama gamefikacija sadržaja u Articulate Storyline, te također kreiranje kompleksnih animacija unutar Adobe Animate.",

    "aidar-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "aidar-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "aidar-about-short" => "Ćao :)  Moje ime je Aida i ja sam e-learning dizajner. Imam 11 godina iskustva u dizajnu i želju za konstantnim učenjem novih stvari. U slobodno vrijeme volim slikati i biti u prirodi. Moja velika ljubav su moj suprug i kućni ljubimci :)",

    "emirm-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "emirm-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "emirm-about-short" => "Zdravo, moje ime je Emir Mekić, ja sam front-end i moodle developer koji voli ptice, prirodu i uživa biti vani. Ne volim sebe da predstavljam prema poslu koji sam obavio. Predstavljam se prema poslu koji želim raditi. Vještine mogu biti naučene, a karakter je svojstvena. Radije bih nastavio učiti, nastaviti postavljati sebi izazove i činiti zanimljive stvari koje su važne.",

    "florinb-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "florinb-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "florinb-about-short" => "Posljednji nekoliko mjeseci napravio sam veliki korak naprijed sa novim iskustvom u web programiranju. Radio sam na konvertovanju velikih eLearning projekata sa starog flasha u html5. Ukoliko tražite developera koji zna biti posvečen vašem projektu, stojim vam na raspolaganju :)",

    "mirzao-long-first-p" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non ligula risus. Fusce quis semper enim, et ultricies mauris. Nam tempor turpis et risus molestie commodo. Sed imperdiet turpis eget sagittis mollis. Duis diam mauris, porttitor ut mauris eget, ultrices ornare dolor. Nam tempor sapien ut erat porttitor aliquet. Sed suscipit justo sit amet placerat rhoncus. Maecenas ornare dignissim porta. Maecenas non massa dui. Integer nec neque hendrerit, ullamcorper risus nec, scelerisque urna.",
    "mirzao-long-second-p" => "Sed condimentum felis vitae pharetra mollis. Donec suscipit tempor metus vel efficitur. In mi diam, consequat ut consequat fringilla, egestas eget lorem. Fusce dignissim felis in enim suscipit feugiat. Nulla posuere ac ante nec volutpat. Aliquam et quam nec est dictum fringilla. Cras auctor ex sit amet dolor lacinia sagittis. Donec tincidunt blandit est in placerat. Praesent ex lorem, tincidunt id odio vel, faucibus scelerisque ante. Duis turpis augue, sodales quis eros eu, rhoncus laoreet diam.",
    "mirzao-about-short" => "Imam 3 godine iskustva u oblasti izrade web i mobilnih aplikacija sa razlicitim oblicima backend arhitektura (monolitne i mikroservisne). Primarno se interesujem za backend stranu izrade web/mobilnih aplikacija i pratece alate i tehnologije. Osnovni programski jezik koji koristim u izradi istih je PHP (Symfony i Laravel framework-s), dok kao DBMS sisteme koristim MySQL i SQL Server. Sto se tice frontend strane izrade web aplikacija, preferiram koristenje cistog JavaScripta u skladu sa najnovijim ECMA standardima, medjutim imam i iskustva u koristenju njenih framework-a kao sto su jQuery, Ember i Polymer.
    Takodje imam veliko interesovanje za Cloud tehnologije i to Google Cloud Platform te tehnologije za upravljanje aplikacijama na serveru kao sto su Docker i Kubernetes. Vise o mojim projektima i mom kodu mozete vidjeti na mojim GitHub javnim repositorijima."
];
